project_id = "mgpotwoxqjnmemrhpddg"

[functions.jupiter-quote]
verify_jwt = false

[functions.jupiter-swap]
verify_jwt = false

[functions.solana-rpc]
verify_jwt = false

[functions.token-metadata]
verify_jwt = false
